### ISSUE TITLE
Odds Server closed markets that has multiple specifiers(except 101/102)

### ISSUE THREAD

**Issue by coder77** [fifasports/UAT#29]
![image](https://user-images.githubusercontent.com/373000/116979577-c1028700-acf7-11eb-9570-fc0676710c6c.png)

One open, the rest will be closed.

`{
                "market_id": NumberInt("107000"),
                "match_id": NumberInt("20010406"),
                "specifier_hash": "first",
                "created_at": "2021-05-04 03:42:29.335",
                "line_number": NumberInt("1"),
                "margin": 0.05,
                "market_type_id": NumberInt("107"),
                "odds_base": {
                    "107001": 1.61198036059762,
                    "107002": 2.96785291587067,
                    "107003": 23.418586205257
                },
                "odds_by_admin": null,
                "odds_by_ticket": null,
                "odds_calibrate": null,
                "odds_display": {
                    "107001": 1.56,
                    "107002": 2.76,
                    "107003": 19.17
                },
                "odds_id": "bfe28591-ac8a-11eb-825e-53330c4fac4b",
                "odds_margin": {
                    "107001": 1.56385780668764,
                    "107002": 2.7698315384869,
                    "107003": 19.1701569807305
                },
                "specifiers": {
                    "first_last": "first"
                },
                "sport_id": NumberInt("1"),
                "status": "open",
                "updated_at": "2021-05-04 08:26:52.705",
                "valid": NumberInt("1")
            },
            {
                "market_id": NumberInt("107000"),
                "match_id": NumberInt("20010406"),
                "specifier_hash": "last",
                "created_at": "2021-05-04 03:42:29.335",
                "line_number": NumberInt("2"),
                "margin": 0.05,
                "market_type_id": NumberInt("107"),
                "odds_base": {
                    "107001": 1.61198036059762,
                    "107002": 2.96785291587067,
                    "107003": 23.418586205257
                },
                "odds_by_admin": null,
                "odds_by_ticket": null,
                "odds_calibrate": null,
                "odds_display": {
                    "107001": 1.56,
                    "107002": 2.76,
                    "107003": 19.17
                },
                "odds_id": "bfe28592-ac8a-11eb-825e-53330c4fac4b",
                "odds_margin": {
                    "107001": 1.56385780668764,
                    "107002": 2.7698315384869,
                    "107003": 19.1701569807305
                },
                "specifiers": {
                    "first_last": "last"
                },
                "sport_id": NumberInt("1"),
                "status": "closed",
                "updated_at": "2021-05-04 08:26:52.705",
                "valid": NumberInt("1")
            }`

**Comment by samuel-zhen** [comment]
Those market (107, 109, 110) generate 2 line by default and since setting.line_present of those market are mostly 1, so one of the lines will be closed. Fixed by set line_present to 2.
![image](https://user-images.githubusercontent.com/25301914/117090520-2489c480-ad8b-11eb-882c-e1b7939aa67d.png)
