### ISSUE TITLE
#46 - Odds is not closing even after the match has already at different stage

### ISSUE THREAD

**Issue by BrianRuchiadi** [fifasports/UAT#46]
Expected odds line are not closing properly. 
On this screenshot, we can see that we are still able to see the 1st Half odds although it is already in HT. 
It should be closed.

Please find out, why it is not, and discuss the possible fix

![image](https://user-images.githubusercontent.com/14333265/119023834-9ccbc900-b9cc-11eb-8b76-3e7004dd46f4.png)

**Comment by samuel-zhen** [comment]
Caused by OS's clock cache.
The clock was not updated when receive mission to close inactive market, so OS unable to determine inactive market properly.
Fix by re-fetch event data when receive mission related to clock, 'close inactive market' is one of them.
