### ISSUE TITLE
Betradar provider send multiple identical match with different match_id

### ISSUE THREAD

**Issue by BrianRuchiadi** [fifasports/UAT#9]
![image](https://user-images.githubusercontent.com/14333265/114498652-abe18d80-9c4e-11eb-8650-f6daef07294d.png)

note :
- should one of the match_id actually already closed, but puller didnt handle?

**Comment by coder77** [comment]
This should not be an issue, unless we handle wrong. Because we cannot prevent it, we should handle it.
